# NumPy Tutorial 

### Why Use NumPy?
- Speed and performance
- Memory efficiency
- Convenient for data analysis and scientific computing
- Foundation for libraries like Pandas, TensorFlow, Scikit-learn
✨ Why Use NumPy?
•	Speed: NumPy arrays are faster than Python lists due to vectorized operations implemented in C.
•	Memory Efficient: Uses less memory compared to standard Python sequences.
•	Convenience: Comes with built-in functions for linear algebra, statistics, reshaping, filtering, etc.
•	Foundation for Data Science: Forms the base for libraries like Pandas, Scikit-learn, TensorFlow, etc.


Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

✨ Why Use NumPy?
•	Speed: NumPy arrays are faster than Python lists due to vectorized operations implemented in C.
•	Memory Efficient: Uses less memory compared to standard Python sequences.
•	Convenience: Comes with built-in functions for linear algebra, statistics, reshaping, filtering, etc.
•	Foundation for Data Science: Forms the base for libraries like Pandas, Scikit-learn, TensorFlow, etc.


In [1]:
import numpy as np
import time
lst = list(range(1000000))
start = time.time()
[ x * 2 for x in lst ]
print("List time:", time.time() - start)



List time: 0.07038116455078125


In [5]:
lst

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [6]:
arr = np.array(lst)
start = time.time()
arr * 2
print("NumPy time:", time.time() - start)

NumPy time: 0.001965045928955078


In [8]:
arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [13]:
import pandas as pd
student_data=pd.read_csv('/Users/manishupadhyay/Downloads/student_performance_large.csv')
student_data

# 1,2,3,4
# 2,4,6,8


# test_array=np.array()


#lis=[1,2,3,4]

Student_ID         Name  Math  Science  English Gender Class  Total  \
0          1001    Student_1    78     65.0     76.0      F   10B    219   
1          1002    Student_1    91     74.0     49.0      M   10B    214   
2          1003    Student_3    68     89.0     49.0      F   10B    206   
3          1004    Student_4    54     64.0     58.0      M   10C    176   
4          1005    Student_5    82     63.0     56.0      F   10C    201   
..          ...          ...   ...      ...      ...    ...   ...    ...   
495        1496  Student_496    87     42.0     82.0      F   10B    211   
496        1497  Student_497    78     92.0     51.0      F   10C    221   
497        1498  Student_498    68     62.0     83.0      F   10D    213   
498        1499  Student_499    81     76.0     75.0      M   10A    232   
499        1500  Student_500    94     92.0     87.0      M   10D    273   

     Percentage  
0     73.000000  
1     71.333333  
2     68.666667  
3     58.666667  
4     67.000000  
..          ...  
495   70.333333  
496   73.666667  
497   71.000000  
498   77.333333  
499   91.000000  

[500 rows x 9 columns]

In [ ]:
# def Mathgrade(x):
#     if x>70:
#         return 'A'
#     else:
#         return 'Fail'


# student_data['new_col']=student_data['Math'].apply(Mathgrade)


In [ ]:
# student_data.columns

In [ ]:
# student_data=student_data[['Student_ID', 'Name', 'Math','new_col', 'Science', 'English', 'Gender', 'Class',
#        'Total', 'Percentage']]
# student_data

In [ ]:
# # df=df.drop(columns=[])

# .apply(lambda x: 'A' if x>70 else'fail' )

In [ ]:
# student_data['new_col1']=student_data['Math'].apply(lambda row: 'Pass' if row>70 else 'Fail')
# student_data
# # new_col = old_col.apply(lambda mani: 'Pass' if mani >70 else fail)

In [ ]:
# student_data['math_grade']=student_data['Math'].apply(lambda row: 'A' if row>70 
#                                                       else ('B' if row>=50  else ('C' if row>=40 else 'Fail' ))   )
# student_data

In [ ]:

# apply func -  5 10
# lambda func- 3  5
# np.where - 1     2


# types of arrays - 1D,2D,3D
# A B C
# [1,2,3]  0,0   0,1  0,2
# [4,5,6]


# [1,2,3]
# 0,1,2



In [ ]:
# pip install numpy

In [ ]:
row X columns

In [ ]:
# np.where // doing certain mathematical calc 

In [11]:
a=np.array(
    [[1,2,3],[4,5,6]]
)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a=np.zeros((4,3)) 
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
b=np.ones((3,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# // full((row,col), values = 7)
c=np.full((3,3),6)  
c

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [27]:
d=np.eye(4)
d


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
a range

In [66]:
## start_value,end_value,step
e=np.arange(0, 10, 20) 
e

# 0- -- -- -- -- -- -- -10            50

array([0])

In [67]:
f=np.linspace(0, 10,20) 
f

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [41]:
# 0---------10     0,1,2,3,4,5,6,7,8,9,10
3.33333333-5

-1.6666666700000001

In [40]:
8.33333333-10

-1.6666666699999997

In [62]:
arr = np.array([[1, 2, 3],[4,5,6]])
arr



array([[1, 2, 3],
       [4, 5, 6]])

In [63]:

a=arr.shape
b=arr.ndim
c=arr.size
d=arr.dtype
print(d)


int64


In [68]:
x = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90],
              [110,120,130], [400, 500, 600], [700, 800, 900]])
x
# rows - 0,1,2
# columns - 0,1,2
# b=x.ndim
# print(b)

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [110, 120, 130],
       [400, 500, 600],
       [700, 800, 900]])

In [78]:
# a=x[0,2]
# print(a)

a=x[:,2] 
print(a)

[ 30  60  90 130 600 900]


In [ ]:
c=x[1, 2]
print(c)

In [79]:
e=x[x>40]
print(e)

[ 50  60  70  80  90 110 120 130 400 500 600 700 800 900]


In [ ]:
a=x[0, 1]
b=x[:, 2]

d=x[x > 50]   


In [80]:
a = np.arange(12)   
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
size=elements = 12 -> (rows,col)

In [94]:
b=a.reshape(12,1)
b

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [ ]:
c=a.reshape(2,6)
c

In [ ]:
d=c.flatten()
print(d)


In [95]:
a = np.array([2, 4, 6])
b = np.array([4, 5, 6])
print(a,b)

[2 4 6] [4 5 6]


In [99]:

c=a + b
d=a / 2
e=a / b
f =a ** 3
print(f)


[  8  64 216]


In [ ]:
np.random.rand()
np.random.randn()
np.random.randint()

In [129]:
arr = np.random.randint(1, 10, size=(3,3))
arr

array([[5, 6, 1],
       [4, 1, 6],
       [2, 5, 3]])

In [109]:
# /// create random +ve integer array
# arr1=np.random.rand(1,10)  
# /// create random -ve integer array
# arr1=np.random.randn(1,20)
# arr1

array([[ 0.32305869,  1.21955093,  0.9843648 , -1.18819494,  0.55777157,
         0.94299319, -1.37498608,  0.25402993, -0.41154016,  1.07490807,
        -2.41886546, -0.28916189,  1.16523234,  0.264986  , -0.09724957,
         0.27873585,  0.96177202,  2.75578476,  1.04132711, -0.13557016]])

In [ ]:

a=np.sum(arr)
b=np.mean(arr)
c=np.std(arr)
d=np.min(arr)
e=np.max(arr)
f=np.median(arr)
g=np.var(arr)
b



In [121]:
import pandas as pd
data = np.random.randint(1, 100, size=(1000000,))
df = pd.DataFrame(data, columns=['values'])
df

values
0           79
1           68
2           61
3           76
4           84
...        ...
999995      51
999996      61
999997      69
999998      31
999999      31

[1000000 rows x 1 columns]

In [122]:
# Using Pandas
start = time.time()
pd_result = df['values'].mean()
end = time.time()
print("Pandas Mean:", pd_result, "Time:", end - start)

Pandas Mean: 49.954246 Time: 0.007284879684448242


In [123]:
# Using NumPy
start = time.time()
np_result = np.mean(df['values'].values)   # convert Series to numpy array
end = time.time()
print("NumPy Mean:", np_result, "Time:", end - start)


NumPy Mean: 49.954246 Time: 0.003498077392578125


In [ ]:
(1+27+97+67)/4

In [124]:
arr = np.random.randint(1, 10, size=(2,2,1))

arr1 = np.random.randint(1, 15, size=(4,4,3))


In [130]:
arr

array([[5, 6, 1],
       [4, 1, 6],
       [2, 5, 3]])

In [ ]:
arr1

In [ ]:
arr2=arr+arr1
arr2

In [131]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b=np.sum(arr, axis=0) --> columns
c=np.sum(arr, axis=1) --> rows
b

array([11, 12, 10])

In [132]:
c

array([12, 11, 10])

In [136]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 0, 1],[7,8,9]])
c=a * b
c

array([[ 1,  0,  3],
       [28, 40, 54]])

In [134]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
b

array([[1, 0, 1],
       [7, 8, 9]])

In [ ]:
a = np.array([1, 2, 3,4,5,6])
b = a
c = a.copy()
b[3:] = 100
b

In [ ]:
a=np.random.rand(3,3)
b=np.random.randn(4,3)
c=np.random.randint(0, 10, (2,3))
d=np.random.seed(2)
print(c)

In [ ]:
1-> []
2-> []
3-> []
4-> []
5-> []
6-> []
7-> []

In [141]:
c=np.random.randint(0, 10, (2,3))
c

array([[9, 4, 2],
       [1, 0, 1]])

In [160]:
np.random.seed(8)
c=np.random.randint(0, 10, (5,5))
c

array([[3, 4, 1, 9, 5],
       [8, 3, 8, 0, 5],
       [1, 3, 9, 2, 2],
       [6, 8, 9, 3, 4],
       [5, 5, 7, 9, 2]])

In [ ]:
np.random.seed(67)

In [ ]:
c=np.random.rand(1,8)
c

In [3]:
arr = np.array([1, 2, np.nan, 2])
arr 

array([ 1.,  2., nan,  2.])

In [4]:
a=np.isnan(arr)
a


array([False, False,  True, False])

In [5]:
b=np.nanmean(arr)
b

1.6666666666666667

In [165]:
5/3

1.6666666666666667

In [6]:
arr = np.array([3, 1, 2, 1, 4])
arr

array([3, 1, 2, 1, 4])

In [7]:

a=np.sort(arr)
a

array([1, 1, 2, 3, 4])

In [8]:
b=np.unique(arr)
b

array([1, 2, 3, 4])

In [9]:
arr

array([3, 1, 2, 1, 4])

In [10]:
a

array([1, 1, 2, 3, 4])

In [11]:
c=np.concatenate([arr, a])
c

array([3, 1, 2, 1, 4, 1, 1, 2, 3, 4])

In [ ]:

d=np.where(arr > 2, 1,0)
d
# true,False


df["new_col"] = np.where(df["previous_col"] > 5, "high", )

In [14]:
def Mathgrade(x):
    if x>70:
        return 'A'
    else:
        return 'Fail'


student_data['new_col']=student_data['Math'].apply(Mathgrade)


In [15]:
student_data

Student_ID         Name  Math  Science  English Gender Class  Total  \
0          1001    Student_1    78     65.0     76.0      F   10B    219   
1          1002    Student_1    91     74.0     49.0      M   10B    214   
2          1003    Student_3    68     89.0     49.0      F   10B    206   
3          1004    Student_4    54     64.0     58.0      M   10C    176   
4          1005    Student_5    82     63.0     56.0      F   10C    201   
..          ...          ...   ...      ...      ...    ...   ...    ...   
495        1496  Student_496    87     42.0     82.0      F   10B    211   
496        1497  Student_497    78     92.0     51.0      F   10C    221   
497        1498  Student_498    68     62.0     83.0      F   10D    213   
498        1499  Student_499    81     76.0     75.0      M   10A    232   
499        1500  Student_500    94     92.0     87.0      M   10D    273   

     Percentage new_col  
0     73.000000       A  
1     71.333333       A  
2     68.666667    Fail  
3     58.666667    Fail  
4     67.000000       A  
..          ...     ...  
495   70.333333       A  
496   73.666667       A  
497   71.000000    Fail  
498   77.333333       A  
499   91.000000       A  

[500 rows x 10 columns]

In [16]:
student_data['new_col_1']=np.where(student_data['Math']>70,'A','Fail')
student_data

Student_ID         Name  Math  Science  English Gender Class  Total  \
0          1001    Student_1    78     65.0     76.0      F   10B    219   
1          1002    Student_1    91     74.0     49.0      M   10B    214   
2          1003    Student_3    68     89.0     49.0      F   10B    206   
3          1004    Student_4    54     64.0     58.0      M   10C    176   
4          1005    Student_5    82     63.0     56.0      F   10C    201   
..          ...          ...   ...      ...      ...    ...   ...    ...   
495        1496  Student_496    87     42.0     82.0      F   10B    211   
496        1497  Student_497    78     92.0     51.0      F   10C    221   
497        1498  Student_498    68     62.0     83.0      F   10D    213   
498        1499  Student_499    81     76.0     75.0      M   10A    232   
499        1500  Student_500    94     92.0     87.0      M   10D    273   

     Percentage new_col new_col_1  
0     73.000000       A         A  
1     71.333333       A         A  
2     68.666667    Fail      Fail  
3     58.666667    Fail      Fail  
4     67.000000       A         A  
..          ...     ...       ...  
495   70.333333       A         A  
496   73.666667       A         A  
497   71.000000    Fail      Fail  
498   77.333333       A         A  
499   91.000000       A         A  

[500 rows x 11 columns]

In [ ]:
student_data['new_col_2']=np.where(student_data['Math']>70,'A',student_data['Math']>50,'B','FAil')
student_data

In [ ]:
np.where(cond,True,Cond,True,
        Cond,True,False)

English -> >70,A
>50-> B
>40 -> C
Else Fail

In [ ]:
np.where(student_data['Math']>70, 'A',np.where(student_data['Math']>50, 'B','Fail'))

### Practice Exercises
1. Create a 5x5 array of random integers 0–100
2. Replace all even numbers with 0
3. Find max value in each row
4. Find mean of each column
5. Flatten, sort, and get unique elements

import pandas as pd
import sqlite3


connection =sqlite3.connect(connection_link)

df = pd.read_sql("SELECT * FROM students", connection)


<!-- df.to_excel('path/new_name_for_file.xlsx')
 -->